# Generated by Django 6.0.6 on 2026-06-08 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_id', models.CharField(max_length=20)),
                ('department_name', models.CharField(max_length=50)),
                ('department_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='employee_department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.department'),
        ),
    ]
